### ISSUE TITLE
VMWare.VimAutomation.Srm module is not loaded

### ISSUE THREAD

**Issue by flegmatoid** [benmeadowcroft/SRM-Cmdlets#20]
I'm using 6.5 R1

Upon importing Meadowcroft.Srm.psd1 I get the error message that VMWare.VimAutomation.Srm module is not loaded.
I don't seem to find it among PowerCLI modules either. Couple of SRM *.dll's seem to exist under VMWare.Vim.Automation.Core, but loading .Core has no effect on the error.
Bypassing this and directly importing the .psm1 goes well, but Get-SrmConfigReport (from the example) fails with [VMware.VimAutomation.Srm.Types.V1.SrmServer[ - make sure that module containing this type is loaded.

**Comment by benmeadowcroft** [comment]
The minimum supported version of PowerCLI for v0.2 of the cmdlets is actually 6.5.1, this is actually different from 6.5 R1! Very confusing I know.

I would suggest either upgrading to a newer version of PowerCLI available from the Powershell gallery, as [described in the PowerCLI blog](https://blogs.vmware.com/PowerCLI/2017/08/updating-powercli-powershell-gallery.html), or using an [earlier version of the cmdlets](https://github.com/benmeadowcroft/SRM-Cmdlets/releases/tag/v0.1) that supported earlier versions of PowerCLI.
